# Generated by Django 4.1.1 on 2023-01-01 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={"verbose_name": "Wallet", "verbose_name_plural": "Wallets"},
        ),
        migrations.AlterModelOptions(
            name="walletcurrency",
            options={"verbose_name": "Wallet Currency", "verbose_name_plural": "Wallet Currencies"},
        ),
        migrations.AlterField(
            model_name="wallet",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Owner"
            ),
        ),
    ]
