# Generated by Django 4.1.1 on 2023-01-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_wallet_options_alter_walletcurrency_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletcurrency",
            name="symbol",
            field=models.CharField(
                choices=[("&#8358", "Naira")], default="&#8358", max_length=10, verbose_name="Symbol"
            ),
        ),
    ]
